INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Penny", "dwd", "#", "Feb 7", "Feb 28");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Penny", "dwd", "#", "Feb 7", "Feb 28");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Penny", "dwd", "#", "Feb 7", "Feb 28");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Penny", "dwd", "#", "Feb 7", "Feb 28");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Penny", "dwd", "#", "Feb 7", "Feb 28");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Penny", "dwd", "#", "Feb 7", "Feb 28");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Penny", "dwd", "#", "Feb 7", "Feb 28");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Penny", "dwd", "#", "Feb 7", "Feb 28");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Penny", "dwd", "#", "Feb 7", "Feb 28");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Penny", "dwd", "#", "Feb 7", "Feb 28");
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);



